// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetCharacters(arg1:string):Promise<main.IdealLimitDataResponse>;

export function Greet(arg1:string):Promise<string>;
